package com.myspace.procurement_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Order Info")
public class OrderInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Item Name")
	private java.lang.String item;
	@org.kie.api.definition.type.Label("Supplier Name")
	private java.lang.String supplier;
	@org.kie.api.definition.type.Label("Target Price")
	private float targetPrice;
	@org.kie.api.definition.type.Label("Supplier Price")
	private float supplierPrice;
	@org.kie.api.definition.type.Label("Urgency")
	private java.lang.String urgency;
	public OrderInfo() {
	}

	public java.lang.String getItem() {
		return this.item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	public java.lang.String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(java.lang.String supplier) {
		this.supplier = supplier;
	}

	public float getTargetPrice() {
		return this.targetPrice;
	}

	public void setTargetPrice(float targetPrice) {
		this.targetPrice = targetPrice;
	}

	public float getSupplierPrice() {
		return this.supplierPrice;
	}

	public void setSupplierPrice(float supplierPrice) {
		this.supplierPrice = supplierPrice;
	}

	public java.lang.String getUrgency() {
		return this.urgency;
	}

	public void setUrgency(java.lang.String urgency) {
		this.urgency = urgency;
	}

	public OrderInfo(java.lang.String item, java.lang.String supplier,
			float targetPrice, float supplierPrice, java.lang.String urgency) {
		this.item = item;
		this.supplier = supplier;
		this.targetPrice = targetPrice;
		this.supplierPrice = supplierPrice;
		this.urgency = urgency;
	}

}